"""ODCS v3 (Open Data Contract Standard) parser → canonical OSI dict.

Schwarz has committed to ODCS as the contract-of-record for their data
products. ODCS describes the *physical and governance* face of a dataset:
schema, server, quality rules, SLAs, ownership. OSI describes the *semantic
and agentic* face: metrics, dimensions, synonyms, AI instructions.

ODCS does not carry metric definitions — those live in OSI or in the Metric
View YAML. So `odcs_to_osi()` produces a fields-only OSI model: dimensions,
description, ai_instructions and the Databricks FQN are populated from the
ODCS server block. Metrics start empty and are expected to be merged from a
companion OSI file (typically generated by `osi_bridge.exporter` from the
backing Metric View).

The intent is that an ODCS file is the *source of truth*, and the OSI file is
the *runtime projection* the bridge serves. The merge step lives in the
ingestion script (`scripts/ingest_models.py`).
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def load_odcs_yaml(path: str | Path) -> dict[str, Any]:
    """Load an ODCS YAML file. Performs only the minimal validation needed
    for `odcs_to_osi()` to work — the rest of the document round-trips."""
    with open(path) as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: ODCS document must be a mapping")
    if data.get("kind") not in ("DataContract", None):
        # `kind` is recommended in v3, optional in earlier; warn-via-exception
        # only on an unexpected value.
        raise ValueError(f"{path}: expected kind: DataContract, got {data.get('kind')!r}")
    if "schema" not in data:
        raise ValueError(f"{path}: ODCS document must contain a 'schema' block")
    return data


def _custom_prop(props: list[dict[str, Any]] | None, key: str) -> Any:
    """Look up an ODCS customProperties entry by `property` name."""
    for p in props or []:
        if p.get("property") == key:
            return p.get("value")
    return None


def _osi_field_from_property(prop: dict[str, Any]) -> dict[str, Any]:
    cp = prop.get("customProperties") or []
    synonyms = _custom_prop(cp, "ai_synonyms") or _custom_prop(cp, "synonyms") or []
    display_name = _custom_prop(cp, "display_name") or prop["name"]
    is_time = (
        _custom_prop(cp, "is_time")
        if _custom_prop(cp, "is_time") is not None
        else prop.get("logicalType") in ("date", "timestamp")
    )
    expr = _custom_prop(cp, "sql_expression") or prop["name"]

    return {
        "name": prop["name"],
        "description": prop.get("description") or prop["name"],
        "expression": [{"dialect": "Databricks", "sql": expr}],
        "dimension": {"is_time": bool(is_time)},
        "ai_context": {
            "synonyms": list(synonyms),
            "display_name": display_name,
        },
    }


def _databricks_fqn(odcs: dict[str, Any], schema_block: dict[str, Any]) -> str:
    """Compose <catalog>.<schema>.<physicalName> from the first ODCS server entry.

    ODCS allows multiple servers (production, staging, …). We pick the first
    `databricks` server; the OSI custom_extensions can be overridden post-load.
    """
    servers = odcs.get("servers") or []
    db_server = next((s for s in servers if s.get("type") == "databricks"), None)
    if db_server is None and servers:
        db_server = servers[0]
    catalog = (db_server or {}).get("catalog", "<catalog>")
    schema = (db_server or {}).get("schema", "osi_demo")
    physical = schema_block.get("physicalName") or schema_block["name"]
    return f"{catalog}.{schema}.{physical}"


def odcs_to_osi(odcs: dict[str, Any], *, metrics: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Project an ODCS v3 contract into the canonical OSI dict shape.

    `metrics` is optional. ODCS itself does not model metrics; pass any
    OSI-shape metric blocks you have (e.g. exported from a Databricks Metric
    View by `osi_bridge.exporter`) and they will be inlined under the OSI
    `metrics` key. If omitted, the resulting model has an empty `metrics:`
    list and queries will fail until metrics are merged in.
    """
    if "schema" not in odcs:
        raise ValueError("ODCS document is missing the 'schema' block")
    schema_block = odcs["schema"][0]
    description = (odcs.get("description") or {}).get("purpose") or odcs.get("name") or schema_block["name"]
    usage = (odcs.get("description") or {}).get("usage")
    limitations = (odcs.get("description") or {}).get("limitations")
    instructions_parts: list[str] = []
    if usage:
        instructions_parts.append(usage)
    if limitations:
        instructions_parts.append(f"Limitations: {limitations}")
    instructions = " ".join(instructions_parts) or (
        f"Semantic model derived from ODCS contract '{odcs.get('id', odcs.get('name', '<unnamed>'))}'."
    )

    name = schema_block.get("physicalName") or schema_block["name"]
    fields = [_osi_field_from_property(p) for p in schema_block.get("properties", [])]
    fqn = _databricks_fqn(odcs, schema_block)

    return {
        "version": "1.0",
        "semantic_model": [
            {
                "name": name,
                "description": description,
                "ai_context": {"instructions": instructions},
                "datasets": [
                    {
                        "name": name,
                        "source": fqn,
                        "fields": fields,
                    }
                ],
                "metrics": list(metrics or []),
                "custom_extensions": {
                    "databricks": {
                        "metric_view_fqn": fqn,
                        "query_pattern": (
                            "SELECT MEASURE(<metric>), <dims> FROM <fqn> "
                            "WHERE <filters> GROUP BY <dims>"
                        ),
                    },
                    "odcs": {
                        "id": odcs.get("id"),
                        "version": odcs.get("version"),
                        "domain": odcs.get("domain"),
                        "data_product": odcs.get("dataProduct"),
                        "owner": _odcs_owner(odcs),
                        "support_channel": _odcs_support(odcs),
                    },
                },
            }
        ],
    }


def _odcs_owner(odcs: dict[str, Any]) -> str | None:
    for member in odcs.get("team") or []:
        if member.get("role") == "owner":
            return member.get("username") or member.get("name")
    return None


def _odcs_support(odcs: dict[str, Any]) -> str | None:
    support = odcs.get("support") or []
    if support:
        return support[0].get("channel")
    return None


def merge_metrics_from_osi(osi_from_odcs: dict[str, Any], osi_from_yaml: dict[str, Any]) -> dict[str, Any]:
    """Take metrics from a Metric-View-derived OSI and inline them into the
    ODCS-derived OSI. Used by the ingestion script."""
    src_metrics = osi_from_yaml["semantic_model"][0].get("metrics", [])
    osi_from_odcs["semantic_model"][0]["metrics"] = list(src_metrics)
    return osi_from_odcs
